services:
    supporthelper-api:
        build: 
            context: .
            dockerfile: src/SupportHelper.API.WebApi/Dockerfile
        container_name: suppoerhelper-api
        ports:
            - "8085:8085"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8085
            - ConnectionStrings__SQLServer=Server=181.215.134.154,1433;Database=DB_SUPPORTHELPER;User Id=app;Password=W2knaft@123;TrustServerCertificate=True;
            - ConnectionStrings__Redis=localhost:6379

    redis:
        container_name: redis
        image: redis:bookworm
        command: >
            redis-server --port 6379 --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - "6379:6379"

volumes:
    redis_data: