<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\SupportHelper.Exceptions\SupportHelper.Exceptions.csproj" />
    <ProjectReference Include="..\..\shared\SupportHelper.RabbitMQ\SupportHelper.RabbitMQ.csproj" />
    <ProjectReference Include="..\SupportHelper.Domain\SupportHelper.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="HttpServices\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.1" />
  </ItemGroup>

</Project>
