// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportHelper.API.Infra.Data.Context;

#nullable disable

namespace SupportHelper.API.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportHelper.API.Domain.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("COL_CURRENTUSERNAME")
                        .HasColumnOrder(4);

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("COL_DOMAINNAME")
                        .HasColumnOrder(5);

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("CHAR(14)")
                        .HasColumnName("COL_HOSTNAME")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsConnected")
                        .HasColumnType("BIT")
                        .HasColumnName("COL_ISCONNECTED")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("COL_LASTUPDATE")
                        .HasColumnOrder(10);

                    b.Property<string>("OperationalSystem")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("COL_OPERATIONALSYSTEM")
                        .HasColumnOrder(7);

                    b.Property<bool>("SgpIsRunning")
                        .HasColumnType("BIT")
                        .HasColumnName("COL_SGPISRUNNING")
                        .HasColumnOrder(3);

                    b.Property<string>("UpTime")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("COL_UPTIME")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasAlternateKey("Hostname");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.ToTable("TB_MACHINE", (string)null);
                });

            modelBuilder.Entity("SupportHelper.API.Domain.Entities.NetworkBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("COL_ID")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COL_DESCRIPTION")
                        .HasColumnOrder(5);

                    b.Property<bool>("InUse")
                        .HasColumnType("BIT")
                        .HasColumnName("COL_INUSE")
                        .HasColumnOrder(4);

                    b.Property<string>("Ipv4")
                        .IsRequired()
                        .HasColumnType("CHAR(15)")
                        .HasColumnName("COL_IPV4")
                        .HasColumnOrder(2);

                    b.Property<string>("Ipv6")
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("COL_IPV6")
                        .HasColumnOrder(6);

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("CHAR(12)")
                        .HasColumnName("COL_MACADRESS")
                        .HasColumnOrder(3);

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("FK_MACHINE")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasAlternateKey("MacAddress");

                    b.HasIndex("MachineId");

                    b.ToTable("TB_NETWORKBOARD", (string)null);
                });

            modelBuilder.Entity("SupportHelper.API.Domain.Entities.Machine", b =>
                {
                    b.OwnsOne("SupportHelper.API.Domain.Entities.ValueObjects.SignalR", "SignalR", b1 =>
                        {
                            b1.Property<int>("MachineId")
                                .HasColumnType("int");

                            b1.Property<string>("ConnectionId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR(100)")
                                .HasColumnName("COL_SIGNALR_CONNECTIONID")
                                .HasColumnOrder(8);

                            b1.Property<bool>("IsActive")
                                .HasColumnType("BIT")
                                .HasColumnName("COL_SIGNALR_ISACTIVE")
                                .HasColumnOrder(9);

                            b1.HasKey("MachineId");

                            b1.ToTable("TB_MACHINE");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.Navigation("SignalR")
                        .IsRequired();
                });

            modelBuilder.Entity("SupportHelper.API.Domain.Entities.NetworkBoard", b =>
                {
                    b.HasOne("SupportHelper.API.Domain.Entities.Machine", "Machine")
                        .WithMany("NetworkBoards")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("SupportHelper.API.Domain.Entities.Machine", b =>
                {
                    b.Navigation("NetworkBoards");
                });
#pragma warning restore 612, 618
        }
    }
}
