version: '2.39.2'

services:
    couchdb:
        image: couchdb:3.5.0
        container_name: couchdb_developed
        environment:
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: admin
        ports:
            - "5984:5984"
        volumes:
            - couchdb_data:/opt/couchdb/data
        networks:
            - backend_dev_network

volumes:
    couchdb_data:

networks:
    backend_dev_network:
        driver: bridge